### ISSUE TITLE
Python 2.6 issue with deepcopy'ing complex objects

### ISSUE THREAD

**Issue by nicolaiarocci** [nicolaiarocci/cerberus#147]
See discussion in nicolaiarocci/eve#701.

**Comment by nicolaiarocci** [comment]
I have a 0.9.2 branch up for testing (see f12e3ff). I plan on releasing Cerberus 0.9.2 next week (and Eve 0.6 shortly after that).

**Comment by funkyfuture** [comment]
i propose to add a copy_document-function to utils.py that acts according to the used Python-version. if i remember correctly deepcopy is used because there were  issues when a document is normalized.
i wonder that 2.6 is still used anyway. its [EOL was reached about two years ago]( https://www.python.org/dev/peps/pep-0361/). which imho would even justify to drop its support.

**Comment by nicolaiarocci** [comment]
Unfortunately Python 2.6 is still widely used, especially in academia. I did some consulting for a UK University this summer, and they were using Eve with Python 2.6. 

I did some research and I could not find a reference to an issue with shallow copies, except for a suggestion to use deepcopy for increased isolation. Maybe I did not look long enough, though. 

Unless we have evidence of issues with shallow copies we might as well go with them instead of adding (apparently) unneeded complexity.

**Comment by funkyfuture** [comment]
it were [my concerns](https://github.com/nicolaiarocci/cerberus/pull/71#issuecomment-101041695) that issues could arise, not actual issues.

however i still have these concerns, especially regarding nested documents. but i'm not sure whether this is justified. it's possible that documents are deepcopied implicitly.

we should add tests to check that there are no sideeffects first.

**Comment by funkyfuture** [comment]
just out of interest:

> I did some consulting for a UK University this summer, and they were using Eve with Python 2.6.

what OS were they using? did they reason why they don't upgrade to 2.7?

**Comment by dkellner** [comment]
I did some further investigations regarding the deepcopying of file objects. Unfortunately, even Python 2.7 does not throw an Exception in this case:

```python
f = open(__file__, 'r')
g = copy.deepcopy(f)
g.read()  # I/O operation on closed file
```

Consider the following test for this case:
```python
    def test_normalized_document_with_file_handle(self):
        schema = {'revision': {'coerce': int}}
        document = {'revision': '5', 'file': NamedTemporaryFile(mode='w+')}
        document['file'].write(r'foobar')
        document['file'].seek(0)
        v = Validator(schema, allow_unknown=True)
        self.assertTrue(v.validate(document))
        normalized = v.document
        self.assertEqual(normalized['revision'], 5)
        self.assertEqual(normalized['file'].read(), 'foobar')
        document['file'].close()
        normalized['file'].close()
```

It fails in current master for 2.6, 2.7 and PyPy (because of deepcopy), raising "ValueError: I/O operation on closed file". However, it works in all Python versions using the shallow-copy approach in 0.9.2.

**Comment by dkellner** [comment]
To make things complicated - and to justify funkyfuture's concerns:

```python
    def test_coerce_in_subschema_not_destructive(self):
        schema = {'thing': {'type': 'dict',
                            'schema': {'amount': {'coerce': int}}}}
        document = {'thing': {'amount': '2'}}
        v = Validator(schema)
        v.validate(document)
        normalized = v.document
        self.assertEqual(document['thing']['amount'], '2')
        self.assertEqual(normalized['thing']['amount'], 2)
```

This will fail in master if shallow copy is used instead of deepcopy, as document gets changed too. I was not able to find a similar testcase for 0.9.2, as subschema coercion seems not to be supported there.
