### ISSUE TITLE
Version links in documentation point at Eve docs instead of Cerberus

### ISSUE THREAD

**Issue by Railslide** [nicolaiarocci/cerberus#170]
When trying to switch between versions (e.g. between `latest` and `stable`) of the docs it opens the chosen version of the Eve project documentation instead of Cerberus.

To reproduce:
- go to http://docs.python-cerberus.org/en/latest/
- from the version menu (in the right bottom corner of the page), select any version

Download and Github links work as expected

**Comment by nicolaiarocci** [comment]
Hello, thanks for reporting this. It looks like it is a Reat the Doc issue though, I opened a [ticket there](https://github.com/rtfd/readthedocs.org/issues/1819). Let's see if we get any advice/fix before I re-build the whole project there.

**Comment by nicolaiarocci** [comment]
In order to mitigate this issue, and also because a lot of people keep emailing me since the documented features are not (yet) available in the released package, I switched the default documentation version to "stable". 

Until this issue is solved, those interested can always look at the "latest" (development) docs at https://cerberus.readthedocs.org/en/latest/

**Comment by nicolaiarocci** [comment]
This should now be solved. Had to delete and rebuilt the whole Read The Docs project.
