### ISSUE TITLE
Update pip source code

### ISSUE THREAD

**Issue by Pithikos** [nicolaiarocci/cerberus#204]
Thanks a of for the great work on this project. It's just such a big pleasure going through the docs! I might have stumbled into a bug for my case usage but after some time I spent with it it seems that it has been fixed but the pip package has not been updated.

Code snippet for reproducing bug

```python
import cerberus
import yaml

schema = {
    'exec' : {  'type' : 'string' },
    'shell' : { 'type' : 'string' },
    'commands' : {
        'type' : 'list',
        'schema' : {
            'type' : 'dict',
            'propertyschema': {
                'type' : 'string',
                'allowed': ['exec', 'shell']
            }
        }
    }
}

validator = cerberus.Validator(schema)

yml = '''
commands:
    - exec: 'echo 1'
    - exec: 'echo 2'
'''
assert validator.validate(yaml.load(yml)) == True

yml = '''
commands:
    - exec: 'echo 1'
    - blah: 'echo 2'
'''
assert validator.validate(yaml.load(yml)) == False

print(validator.errors)
```

Running after a `pip install cerberus` gives an exception as seen in the output.

```
Traceback (most recent call last):
  File "test.py", line 34, in <module>
    assert validator.validate(yaml.load(yml)) == False
  File "/home/manos/anaconda/lib/python2.7/site-packages/cerberus/cerberus.py", line 236, in validate
    return self._validate(document, schema, update=update, context=context)
  File "/home/manos/anaconda/lib/python2.7/site-packages/cerberus/cerberus.py", line 282, in _validate
    self._validate_definition(definition, field, value)
  File "/home/manos/anaconda/lib/python2.7/site-packages/cerberus/cerberus.py", line 341, in _validate_definition
    definition.get('allow_unknown'))
  File "/home/manos/anaconda/lib/python2.7/site-packages/cerberus/cerberus.py", line 595, in _validate_schema
    validator.validate({i: value[i]}, context=self.document)
  File "/home/manos/anaconda/lib/python2.7/site-packages/cerberus/cerberus.py", line 236, in validate
    return self._validate(document, schema, update=update, context=context)
  File "/home/manos/anaconda/lib/python2.7/site-packages/cerberus/cerberus.py", line 282, in _validate
    self._validate_definition(definition, field, value)
  File "/home/manos/anaconda/lib/python2.7/site-packages/cerberus/cerberus.py", line 349, in _validate_definition
    validator(definition[rule], field, value)
  File "/home/manos/anaconda/lib/python2.7/site-packages/cerberus/cerberus.py", line 627, in _validate_propertyschema
    self._error(field, error)
  File "/home/manos/anaconda/lib/python2.7/site-packages/cerberus/cerberus.py", line 360, in _error
    field_errors.extend(_error)
TypeError: 'int' object is not iterable
```

Running against the codebase on github seems to work fine though as seen below.

```
$ python2.7 -B test.py 
{'commands': {1: {'blah': 'unallowed value blah'}}}
```

**Comment by funkyfuture** [comment]
> It's just such a big pleasure going through the docs!

thanks! (i guess also on behalf of @nicolaiarocci.) it's a tough task to keep a documentation up-to-date, comprehensible and well-arranged. you're welcome to submit any amandment that improves it.

when you wrote your schema, did you consult the [stable](docs.python-cerberus.org/en/stable/) or the [latest](docs.python-cerberus.org/en/latest/) documentation?

i don't know without research which change would have fixed this. if you need it fixed in a `0.9.3` release, i suggest you figure it out.

i also found your initial post interesting, as there are some requests concerning schema recursion and serialization. i once wrote an [ad-hoc proposal](https://github.com/nicolaiarocci/cerberus/issues/150#issuecomment-143320283) and your initial request was somehow similar.

i think this approach is attractive due to two reasons:
- it allows serialization of 'recursive' / 'reusable' schemas
- it's more explicit than a detection, thus propably much easier to implement and safe to sideeffects

@nicolaiarocci should i write a summary about all this to discuss and decide how this should be designed? (it may take some time, i currently have some projects that need attention.)

**Comment by nicolaiarocci** [comment]
> i also found your initial post interesting
link?

In general, I feel like v1.0 release is our top priority right now, so everybody can take advantage of "new Cerberus" (I've been having people email me about next release for a good while, too). After that, since we won't be beta anymore and we are going to adopt SemVer, we aren't going to break backward compatibility since 2.0 is out, and that is very unlikely to happen for a very long time.

**Comment by Pithikos** [comment]
Probably there is no link. Regarding my initial post, it was mostly about on what I was trying to achieve and how that was possible with Cerberus. Namely I was trying to achieve some sort of recursive schema like below.

```python
schema = {
    'exec' : {  'type' : 'string' },
    'shell' : { 'type' : 'string' },
    'commands' : {
        'type' : 'list',
        'any_in_schema' : ['exec', 'shell']
    }
}
```

So the juicy part is that I want to my `commands` to make use of what I defined in my schema about `exec` and `shell`.

I solved my issue for the moment with the schema below

```python
schema = {
    'exec' : {  'type' : 'string' },
    'shell' : { 'type' : 'string' },
    'commands' : {
        'type' : 'list',
        'schema' : {
            'type' : 'dict',
            'propertyschema': {
                'type' : 'string',
                'allowed': ['exec', 'shell']
            }
        }
    }
}
```

It seems to work but I assume that is because it happens that `exec` and `shell` take `string` as values. I assume that this would break if I ever had to change the definitions of exec and shell to something else than string.

**Comment by funkyfuture** [comment]
the first two field definitions in the 1st-level-schema don't matter for your initial example.
but otherwise it seems like a proper solution to your problem.
