### ISSUE TITLE
How a validation schema in a docstring would be seperated (or be found otherwise)

### ISSUE THREAD

**Issue by mbalser** [nicolaiarocci/cerberus#217]
Commit 76fd4ce1fbe23c06d240c78aa871e88d1c53523d introduced a bug which renders using subclasses to enhance cerberus with custom validators and custom types impossible.

This happens still on HEAD, so I consider this a new bug:

> Traceback (most recent call last):
>   File "test.py", line 17, in <module>
>     validate = MyValidator(schema, purge_unknown=True)
>   File "/opt/provision_env/lib/python3.4/site-packages/cerberus/cerberus.py", line 208, in __init__
>     self.__set_introspection_properties()
>   File "/opt/provision_env/lib/python3.4/site-packages/cerberus/cerberus.py", line 251, in __set_introspection_properties
>     else literal_eval(constraints.lstrip())
>   File "/usr/lib/python3.4/ast.py", line 46, in literal_eval
>     node_or_string = parse(node_or_string, mode='eval')
>   File "/usr/lib/python3.4/ast.py", line 35, in parse
>     return compile(source, filename, mode, PyCF_ONLY_AST)
>   File "<unknown>", line 1
>     Dummy validation for something. 
>                    ^
> SyntaxError: invalid syntax

You can reproduce it with the following script:

```
from cerberus import Validator

class MyValidator(Validator):
    def _validate_something(self, something, field, value):
        """ Dummy validation for something. """
        pass


data = {'name': 'foo'}

schema = {'name': {'type': 'string',
                   'empty': False,
                   'minlength': 1,
                   'maxlength': 64}}

validate = MyValidator(schema, purge_unknown=True)

print(validate.validate(data))
print(validate.errors)
```

**Comment by nicolaiarocci** [comment]
cc @funkyfuture

**Comment by funkyfuture** [comment]
i forgot the docs in that commit, see https://github.com/nicolaiarocci/cerberus/pull/219/commits/0d208e34786be6a8446990027291b347847f8b70#diff-03f9a724476be21f4f66e450a056def9R58

**Comment by mbalser** [comment]
Understood. But this changed handling leaves me with one thing that I can no longer do:
a custom data type that has a value that does not exist yet in the base cerberus.

Example with a uuid object:

```
import uuid
class MyValidator(Validator):
    def _validate_type_uuid(self, field, value):
        """ {'type': 'string'} """
        # would require type "uuid" here...which I just want to define!
        pass

data = {'name': uuid.uuid4()}
[....]
```

How could this be done not only for python "uuid", but also for custom objects?

**Comment by nicolaiarocci** [comment]
yeah this is an issue. Also there are a *lot* of custom validators in the wild right now (mostly Eve validators) and most are going to suffer from this issue. It would be probably be a good idea not to force schema validation or, better, allow to opt out of it. Alternatively, we need to make it work with custom objects as suggeted by @mbalser. This would require a lot of people to go back and fix their existing code (which is bound to happen anyway since there are other breaking changes going on).

**Comment by funkyfuture** [comment]
> a custom data type that has a value that does not exist yet in the base cerberus.

i understand that you mean name by value. and that is not a problem. custom types are discovered. a type is not a rule and you don't need to define anything for them to get them validated.

> But I would rather use the full featureset as I can see its value. For now this provides a quickfix for everyone using custom validation types.

i don't get it.

@nicolaiarocci as @mbalser points out, the opt-out is to not supply a docstring on rules methods.

**Comment by funkyfuture** [comment]
which means it is actually an opt-in to validate schemas concerning custom rules by default already.

**Comment by nicolaiarocci** [comment]
> the opt-out is to not supply a docstring on rules methods.

Yeah but the thing is, people have been using docstrings on custom validators for both types and rules since the first release. And rightfully so as they are standard Python best practice. So when they upgrade they will have to remove docstrings in order to get a fix. That's pretty harsh if you ask me :smile:. If docstrings are there, they are for a good reason (or we have to assume so).

**Comment by mbalser** [comment]
Exactly - docstrings are there for a good reason and can be considered best-practice.
Why not use a prefix like "schema::" inside the docstring to indicate that the schema now follows. It should be pretty easy to implement this even for multi-line schemas as you only need to detect an empty line - like the good old http is doing it to separate headers and body.

This would preserve the current state, extend the functionality and still be pretty much compliant to presumable all kinds of docstring that are currently in use. And people can embedd the schema at any place in the docstring they choose.

**Comment by funkyfuture** [comment]
i was well aware of that conflict when i implemented it, but wanted to wait for feedback on it. now, here it is. though the development of the discussion to that point here is rather confusing. i would suggest to open a new issue to discuss the question how a validation schema in a docstring would be seperated (or be found otherwise) from other content of a docstring.

btw, until now i holded back to begin a `UPGRADING.rst` that documents all breaks from `0.x` to `1.x`, but it seems no more premature to me.

**Comment by nicolaiarocci** [comment]
> Why not use a prefix like "schema::" inside the docstring to indicate that the schema now follows.

This is what I was thinking as well. Maybe @funkyfuture future can experiment with this option a little bit.

> btw, until now i holded back to begin a UPGRADING.rst that documents all breaks from 0.x to 1.x.

Awesome! I was going to ask you to work on something like that :+1:

**Comment by nicolaiarocci** [comment]
PS: I updated the ticket topic. Let's keep talking in here.

**Comment by funkyfuture** [comment]
i don't think keywords or arbritrary seperators are a way to deal with it. the first could possibly used in a docstring's text, the latter may be hard to agree on and will eventually still be not intuitive to everyone.

so i propose that a validation schema is either given as full docstring or seperated by a

    The rule's arguments are validated against this schema:

at the end of a docstring.

it also may lead to less typos in a seperator, assuming that this will be copy-pasted.

**Comment by funkyfuture** [comment]
> Awesome! I was going to ask you to work on something like that

would you provide the part highlighting new features as in your blog posts?

**Comment by nicolaiarocci** [comment]
I like the second option ("The rule's... " at the end of docstring). Leaves docstrings fully functional and still allows for rules validation.

> would you provide the part highlighting new features as in your blog posts?

Sure.
