### ISSUE TITLE
1.0 removes "field" argument from _validate methods

### ISSUE THREAD

**Issue by yohanboniface** [nicolaiarocci/cerberus#263]
I'm not sure why `field` argument has been removed from the `_validate_xxx` methods signature, it's helpful to get the context and to do better checks.

For example:

    def _validate_type_string(self, field, value):
        if value is None and not self.schema[field].get('required'):
            return True
        return super()._validate_type_string(field, value)

I suggest adding it back as it does not cost any cent imho.

Thanks :)

**Comment by funkyfuture** [comment]
the reason was to simplify the interface for **type**-checking methods.

if such state context was provided i would suggest to bind it to an instance property like others to make it more versatile. 

however, in what i read in your example i can think of other ways to handle the question (via schema or custom rule). i would even say you're trying to misuse a type-check there.
